spring.application.name=linebot

line.bot.channel-token=MyptMaoJF7NzPXwDxVkL3IM8QbnNd7PjGFahvqbiNcCB5fPDRlifeFigFZIc1wNXU0zM4tigShV3oD1UfnIe4xT9+7lT1+Bu8xnQBqLN65dXvGA6uAbRwoPNZeUInOSf55zqpPiXjSApSk0ttyJi7AdB04t89/1O/w1cDnyilFU=
line.bot.channel-secret=b2d9d6974028a114176dd32378fde1d7
line.bot.handler.path=/callback
janken.api.url=http://b2240210.cloud.fml.org/api/rek_janken/v1
# これまでのpropertiesの内容の下に追加する。
# また、usernameとpasswordの ******** の部分は、自分の学籍番号 b... に書き換える。

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:~/h2db/ictdev;AUTO_SERVER=TRUE;MODE=PostgreSQL
spring.datasource.username=b2240210
spring.datasource.password=b2240210


#最終課題のために追加
#amazonLambゲートウェイ
bus.api.url=https://q64ccpa1u6.execute-api.us-east-1.amazonaws.com/default/getNextBus
#クラウドサーバー利用のための一文
server.port=${PORT:8080}
